Repository CS2103-AY1819S1-W13-3/main, pull requests merged in 2018-10, with the labels that each got.

#33 Add coveralls pin and acknowledgements for se-edu/addressbook-level4
  README.adoc
Labels: priority:Medium, type.Task

#34 Add config file for reposense
  _reposense/config.json
Labels: priority.High, type.Task

#40 App accepts AttendanceCommand arguments
  src/main/java/seedu/address/logic/commands/AttendanceCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AttendanceCommandParser.java
  src/test/java/seedu/address/logic/commands/AttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/AttendanceCommandParserTest.java
Labels: priority.High

#47 Fix documentation
  README.adoc
  appveyor.yml
  build.gradle
  docs/templates/_header.html.slim
Labels: priority.High

#64 Enhanced find command to find by tags
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/IsTaggedPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.High, type.Enhancement

#75 Calendar v1.3
  .travis.yml
  build.gradle
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/address/model/event/Date.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/EventListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/EventListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/BrowserPanelHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/WebViewUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ScheduleCommandParserTest.java
  src/test/java/seedu/address/model/event/DateTest.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: priority.High

#81 Updated dev guide, Implemented SetTagCommand
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/commands/AttendanceCommand.java
  src/main/java/seedu/address/logic/commands/SetTagCommand.java
  src/main/java/seedu/address/logic/commands/mark/IMarkExecutable.java
  src/main/java/seedu/address/logic/commands/mark/MarkAndCommand.java
  src/main/java/seedu/address/logic/commands/mark/MarkCommand.java
  src/main/java/seedu/address/logic/commands/mark/MarkFindCommand.java
  src/main/java/seedu/address/logic/commands/mark/MarkJoinCommand.java
  src/main/java/seedu/address/logic/commands/mark/MarkShowCommand.java
  src/main/java/seedu/address/logic/commands/mark/MarkSubCommand.java
  src/main/java/seedu/address/logic/commands/mark/MarkSubCommands.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/SetTagCommandParser.java
  src/main/java/seedu/address/model/mark/Mark.java
Labels: feature.Mark, priority:Medium, type.Enhancement

#83 Update sample data
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority:Medium
