Repository CS2103-AY1819S1-W13-3/main, pull requests merged in 2018-11, with the labels that each got.

#88 Mark now properly updates if content is changed
  src/main/java/seedu/address/commons/events/model/PersonChangedEvent.java
  src/main/java/seedu/address/logic/commands/mark/MarkCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/mark/Mark.java
Labels: feature.Mark, priority.High

#93 Style fix for Attendance Command in User Guide
  docs/UserGuide.adoc
Labels: feature.Attendance, priority:Medium

#87 User/Dev-guide updates
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/mark/MarkAndCommand.java
  src/main/java/seedu/address/logic/commands/mark/MarkFindCommand.java
  src/main/java/seedu/address/logic/commands/mark/MarkJoinCommand.java
  src/main/java/seedu/address/logic/commands/mark/MarkShowCommand.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
Labels: feature.Mark, priority:Medium

#102 Fix preliminary bugs encountered through the practice PE.
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/model/event/Date.java
  src/main/java/seedu/address/model/event/Description.java
  src/main/java/seedu/address/model/event/EventName.java
  src/main/java/seedu/address/ui/EventListPanel.java
  src/test/java/seedu/address/model/event/DateTest.java
Labels: severity.Medium

#128 Update Project Docs
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/attendance_diagram1.png
  docs/images/attendance_diagram2.png
  docs/images/attendance_diagram_logic.png
  docs/team/yogtew.adoc
Labels: priority.High, status.Ongoing

#131 Attendance Command uses Mark
  src/main/java/seedu/address/logic/commands/AttendanceCommand.java
  src/main/java/seedu/address/logic/parser/AttendanceCommandParser.java
  src/test/java/seedu/address/logic/commands/AttendanceCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AttendanceCommandParserTest.java
Labels: feature.Attendance

#139 Update App icon
  src/main/resources/images/address_book_32.png
Labels: priority:Medium

#140 Clean up code
  src/main/java/seedu/address/logic/commands/AttendanceCommand.java
  src/main/java/seedu/address/logic/parser/AttendanceCommandParser.java
  src/main/java/seedu/address/model/student/Attendance.java
  src/test/java/seedu/address/logic/commands/AttendanceCommandTest.java
  src/test/java/seedu/address/logic/parser/AttendanceCommandParserTest.java
Labels: priority.High

#141 Edits to Docs
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/yogtew.adoc
Labels: priority.High

#137 Add more tests for ConTAct
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/ui/EventListPanel.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/test/java/seedu/address/model/VersionedCalendarTest.java
  src/test/java/seedu/address/storage/XmlAdaptedStudentTest.java
  src/test/java/seedu/address/storage/XmlAdapterEventTest.java
  src/test/java/seedu/address/testutil/EventUtil.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
  src/test/java/seedu/address/ui/EventListPanelTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/ScheduleCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority:Medium, type.Task

#153 Add Graph Feature
  build.gradle
  docs/GraphPage.html
  docs/js/d3.v3.min.js
  src/main/java/seedu/address/commons/events/ui/ShowGraphRequestEvent.java
  src/main/java/seedu/address/logic/commands/GraphCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/GraphCommandParser.java
  src/main/java/seedu/address/ui/GraphPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/GraphPanelHandle.java
  src/test/java/guitests/guihandles/WebViewUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/ui/GraphPanelTest.java
Labels: type.Epic

#156 Updating UML diagrams and documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/ScheduleSequenceDiagram.pptx
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/ModelClassDiagram.png
  docs/images/ScheduleEventSdForLogic.png
  docs/images/ScheduleEventSequenceDiagram.png
  docs/images/ScheduleExampleForUG.png
  docs/images/ScheduleSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/team/andrewtanjs.adoc
Labels: status.Ongoing

#160 Update Graph Docs
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/GraphCI.png
  docs/images/GraphMockup.png
  docs/images/GraphSD.png
Labels: priority.High, type.Epic

#166 add Cyrus PPP
  docs/DeveloperGuide.adoc
  docs/team/cyrusguo.adoc
Labels: type.Epic
